apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gosl7cll1-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gosl7cll1-go 
  name: gosl7cll1-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: gosl7cll1-go 
